---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hello
  namespace: ${TPL_ENVIRONMENT}
spec:
  replicas: ${TPL_REPLICAS:-3}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: quay.io/strataconsulting/hello_strata:${TPL_ENVIRONMENT:-release}-${WERCKER_GIT_COMMIT}
        ports:
        - name: http-server
          containerPort: 9000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello
  namespace: ${TPL_ENVIRONMENT}
spec:
  scaleTargetRef:
    apiVersion: autoscaling/v1
    kind: Deployment
    name: hello
  minReplicas: 1
  maxReplicas: 26
  targetCPUUtilizationPercentage: 50
